# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
   
      - name: build
        run: swiftc -O main.swift -o textract
      
      - name: Artifact name
        id: artifactname
        run: |
          
          echo "wheelfile=$(ls *.w | head -1)" >> $GITHUB_OUTPUT
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.2.1-node20
        with:
          # Artifact name
          name: textract-${{steps.extract_branch.outputs.branch}}-${{ github.sha }}
          # A file, directory or wildcard pattern that describes what to upload
          path: error
          
